packages:
  - user-apps/*
  - admin-apps/*
  - packages/*
catalog:
  typescript: 5.8.2
  next: 15.2.1
  react: 19.0.0
  react-dom: 19.0.0
  sass: 1.80.6
  clsx: 2.1.1
  tailwindcss: 3.4.17
  tailwind-merge: 3.0.2
  class-variance-authority: 0.7.1
  autoprefixer: 10.4.20
  postcss: 8.5.3
  lucide-react: 0.479.0
  turbo: 2.4.4
  es-toolkit: 1.32.0
  react-intersection-observer: 9.16.0
  '@testing-library/dom': 10.4.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.1.0
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  '@types/node': 22.13.9
  '@types/react': 19.0.10
  '@types/react-dom': 19.0.4
  '@types/jest': 29.5.14
  '@biomejs/biome': 1.9.4
  '@module-federation/rsbuild-plugin': 0.10.0
  '@module-federation/enhanced': 0.10.0
  "@module-federation/dts-plugin": 0.10.0
  '@rsbuild/core': 1.2.15
  '@rsbuild/plugin-react': 1.1.1
  '@chromatic-com/storybook': 3.2.5
  '@storybook/addon-essentials': 8.6.4
  '@storybook/addon-interactions': 8.6.4
  '@storybook/addon-links': 8.6.4
  '@storybook/blocks': '8.5.8'
  '@storybook/react': 8.6.4
  '@storybook/test': 8.6.4
  'storybook': 8.6.4
onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js-pure
  - esbuild
  - sharp
