packages:
  - apps/*
  - packages/*
catalog:
  next: 15.2.1
  typescript: 5.6.3
  react: 19.0.0
  react-dom: 19.0.0
  sass: 1.80.6
  clsx: 2.1.1
  tailwindcss: 3.4.14
  tailwind-merge: 2.5.2
  '@biomejs/biome': 1.9.4
  '@types/node': 22.9.0
  '@types/react': 18.3.12
  '@types/react-dom': 18.3.1
  class-variance-authority: 0.7.0
  autoprefixer: 10.4.20
  postcss: 8.4.47
  ts-node: 10.9.2
  ts-node-dev: 2.0.0
  ts-jest: 29.2.5
  '@testing-library/dom': 10.4.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.1.0
  jest: 29.7.0
  jest-environment-jsdom: 29.7.0
  '@types/jest': 29.5.14
  '@prisma/client': 6.4.1
  prisma: 6.4.1
  lucide-react: 0.460.0
  rimraf: 6.0.1
  dotenv: 16.4.7
  turbo: 2.4.4
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@prisma/client'
  - '@prisma/engines'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
